DROP DATABASE IF EXISTS app_db;
CREATE DATABASE app_db;
USE app_db;

CREATE TABLE userTable(
    
);

CREATE TABLE mainFeed(
    id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(50) NOT NULL,
    message VARCHAR(50) NOT NULL,
    PRIMARY KEY(id)
)

CREATE TABLE dmMessage